version: '3'
services:
  db-application:
    image: postgres
    ports:
      -  "9145:5432"
    environment:
      - "POSTGRES_DB=${APP_DB_NAME}"
  backend:
    build: ../api-server
    ports:
      - "3001:8000"
    environment:
      - LOCAL_PORT=8000
      - APP_DB_HOST=db-application
      - APP_DB_PORT=5432
      - APP_DB_NAME
      - APP_DB_USERNAME
      - APP_DB_PASSWORD
    depends_on:
      - db-application
      - authn
  web-frontend:
    build: ../web-frontend
    ports:
      - "3002:3000"
      - "35729:35729"
    depends_on:
      - backend
      - authn
  db-authn:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis-authn:
    image: redis
  authn:
    image: keratin/authn-server:1.3.0
    ports:
      - "8765:3000"
    environment:
      - DATABASE_URL=mysql://root@db-authn:3306/authn
      - REDIS_URL=redis://redis-authn:6379/0
      - AUTHN_URL=http://authn:3000
      - APP_DOMAINS=localhost
      - SECRET_KEY_BASE
      - PASSWORD_POLICY_SCORE=0
    depends_on:
      - redis-authn
      - db-authn
    command: sh -c "./authn migrate && ./authn server"

  reverseproxy:
    build: ./reverseproxy
    ports:
    - "80:80"
    # environment:
    # - NGINX_HOST=localhost
    # - NGINX_PORT=80
    depends_on:
      - authn
      - backend
      - web-frontend